# Generated by Django 4.1.2 on 2022-10-30 10:17

import car_collection_app.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('year', models.IntegerField(validators=[car_collection_app.web.models.validate_year_in_range])),
                ('image_url', models.URLField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.FloatField()),
            ],
        ),
    ]
